# psnd_xterm.cmake - Embed vendored xterm.js into a generated C header
#
# Usage:
#   include(psnd_xterm)
#   psnd_generate_xterm_header()   # writes generated/host_web_xterm.h
#
# Emits byte arrays, not string literals: MSVC rejects a string literal over
# 64KB (C1091), and xterm.js is ~280KB.

set(PSND_XTERM_DIR "${PSND_ROOT_DIR}/source/thirdparty/xterm-5.3.0")
set(PSND_XTERM_FIT_DIR "${PSND_ROOT_DIR}/source/thirdparty/xterm-addon-fit-0.8.0")

# Append `static const unsigned char <name>_DATA[]` (NUL-terminated) and a
# `const char *` alias <name> to out_var.
function(_psnd_xterm_embed out_var name path)
    file(READ "${path}" hex HEX)
    string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," hex "${hex}")
    set(${out_var} "${${out_var}}
static const unsigned char ${name}_DATA[] = {
    ${hex}0x00
};
#define ${name} ((const char *)${name}_DATA)
" PARENT_SCOPE)
endfunction()

function(psnd_generate_xterm_header)
    set(inputs
        "${PSND_XTERM_DIR}/xterm.css"
        "${PSND_XTERM_DIR}/xterm.js"
        "${PSND_XTERM_FIT_DIR}/xterm-addon-fit.js"
    )
    set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS ${inputs})

    set(content "/* host_web_xterm.h - generated by scripts/cmake/psnd_xterm.cmake. Do not edit.
 *
 * xterm.js 5.3.0 and xterm-addon-fit 0.8.0 (MIT), from source/thirdparty/.
 */

#ifndef LOKI_HOST_WEB_XTERM_H
#define LOKI_HOST_WEB_XTERM_H
")
    _psnd_xterm_embed(content XTERM_CSS "${PSND_XTERM_DIR}/xterm.css")
    _psnd_xterm_embed(content XTERM_JS "${PSND_XTERM_DIR}/xterm.js")
    _psnd_xterm_embed(content XTERM_FIT_JS "${PSND_XTERM_FIT_DIR}/xterm-addon-fit.js")
    string(APPEND content "\n#endif /* LOKI_HOST_WEB_XTERM_H */\n")

    # Rewrite only on change so a reconfigure does not rebuild the hosts
    set(out "${CMAKE_BINARY_DIR}/generated/host_web_xterm.h")
    if(EXISTS "${out}")
        file(READ "${out}" old)
    endif()
    if(NOT "${old}" STREQUAL "${content}")
        file(WRITE "${out}" "${content}")
        message(STATUS "Generated: ${out}")
    endif()
endfunction()
