/* host_web_ui.h - Shared embedded HTML UI for web and webview hosts
 *
 * This header contains the embedded xterm.js-based UI used by both:
 * - host_web.c (mongoose HTTP/WebSocket server)
 * - host_webview.cpp (native webview window)
 *
 * The JavaScript code detects the environment and uses:
 * - WebSocket for browser mode (when window.psnd is not defined)
 * - Direct JS bindings for webview mode (when window.psnd is defined)
 */

#ifndef LOKI_HOST_WEB_UI_H
#define LOKI_HOST_WEB_UI_H

/* xterm.js paths, served by host_web.c from host_web_xterm.h. host_webview.cpp
 * inlines the same files in place of these tags. */
#define XTERM_CSS_PATH "/xterm.css"
#define XTERM_JS_PATH "/xterm.js"
#define XTERM_FIT_JS_PATH "/xterm-fit.js"

/* Complete embedded xterm.js-based UI - no external files needed */
static const char *EMBEDDED_HTML =
"<!DOCTYPE html>\n"
"<html>\n"
"<head>\n"
"  <meta charset=\"utf-8\">\n"
"  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n"
"  <title>psnd editor</title>\n"
"  <link rel=\"stylesheet\" href=\"" XTERM_CSS_PATH "\">\n"
"  <style>\n"
"    * { box-sizing: border-box; margin: 0; padding: 0; }\n"
"    html, body { height: 100%; background: #1e1e1e; overflow: hidden; }\n"
"    #app { display: flex; flex-direction: column; height: 100%; }\n"
"    #header { display: flex; align-items: center; gap: 12px; padding: 6px 12px;\n"
"              background: #252526; border-bottom: 1px solid #3c3c3c; }\n"
"    .logo { font-weight: bold; color: #4ec9b0; font-family: monospace; }\n"
"    .status { padding: 2px 8px; border-radius: 4px; font-size: 12px; font-family: sans-serif; }\n"
"    .status.connected { background: #4ec9b0; color: #1e1e1e; }\n"
"    .status.disconnected { background: #f44747; color: white; }\n"
"    .mode { padding: 2px 8px; border-radius: 4px; font-size: 12px; background: #569cd6;\n"
"            color: white; text-transform: uppercase; font-family: sans-serif; }\n"
"    .filename { color: #888; font-family: monospace; }\n"
"    .spacer { flex: 1; }\n"
"    .btn { padding: 4px 12px; font-size: 12px; font-family: sans-serif; background: #3c3c3c;\n"
"           color: #ccc; border: 1px solid #555; border-radius: 4px; cursor: pointer; }\n"
"    .btn:hover { background: #4c4c4c; border-color: #666; }\n"
"    .btn:active { background: #2c2c2c; }\n"
"    .btn-play { background: #2d5a2d; border-color: #3d7a3d; }\n"
"    .btn-play:hover { background: #3d6a3d; }\n"
"    .btn-stop { background: #5a2d2d; border-color: #7a3d3d; }\n"
"    .btn-stop:hover { background: #6a3d3d; }\n"
"    #terminal-wrap { flex: 1; padding: 4px; }\n"
"    #terminal { height: 100%; }\n"
"    .xterm { padding: 4px; }\n"
"    #footer { display: flex; justify-content: space-between; padding: 4px 12px;\n"
"              background: #252526; border-top: 1px solid #3c3c3c; font-size: 12px;\n"
"              color: #888; font-family: monospace; }\n"
"  </style>\n"
"</head>\n"
"<body>\n"
"  <div id=\"app\">\n"
"    <header id=\"header\">\n"
"      <span class=\"logo\">psnd</span>\n"
"      <span id=\"status\" class=\"status disconnected\">Disconnected</span>\n"
"      <span id=\"mode\" class=\"mode\"></span>\n"
"      <span id=\"filename\" class=\"filename\"></span>\n"
"      <span class=\"spacer\"></span>\n"
"      <button id=\"btn-play\" class=\"btn btn-play\">Play</button>\n"
"      <button id=\"btn-stop\" class=\"btn btn-stop\">Stop</button>\n"
"      <button id=\"btn-eval\" class=\"btn\">Eval</button>\n"
"    </header>\n"
"    <div id=\"terminal-wrap\"><div id=\"terminal\"></div></div>\n"
"    <footer id=\"footer\">\n"
"      <span id=\"message\"></span>\n"
"      <span id=\"position\"></span>\n"
"    </footer>\n"
"  </div>\n"
"  <script src=\"" XTERM_JS_PATH "\"></script>\n"
"  <script src=\"" XTERM_FIT_JS_PATH "\"></script>\n"
"  <script>\n"
"(function() {\n"
"  var statusEl = document.getElementById('status');\n"
"  var modeEl = document.getElementById('mode');\n"
"  var filenameEl = document.getElementById('filename');\n"
"  var messageEl = document.getElementById('message');\n"
"  var positionEl = document.getElementById('position');\n"
"\n"
"  var term = new Terminal({ cursorBlink: true, fontSize: 14,\n"
"    fontFamily: \"'Consolas', 'Monaco', 'Courier New', monospace\",\n"
"    theme: { background: '#1e1e1e', foreground: '#cccccc', cursor: '#cccccc',\n"
"             selection: 'rgba(255,255,255,0.3)', black: '#1e1e1e', red: '#f44747',\n"
"             green: '#4ec9b0', yellow: '#cca700', blue: '#569cd6', magenta: '#c586c0',\n"
"             cyan: '#9cdcfe', white: '#d4d4d4', brightBlack: '#808080' }});\n"
"  var fitAddon = new FitAddon.FitAddon();\n"
"  term.loadAddon(fitAddon);\n"
"  term.open(document.getElementById('terminal'));\n"
"  fitAddon.fit();\n"
"\n"
"  /* Detect webview mode vs browser mode */\n"
"  /* webview_bind creates window.psnd as a function, not window.psnd.send */\n"
"  var isWebview = typeof window.psnd === 'function';\n"
"  var ws = null, reconnectTimeout = null;\n"
"  var HL_COLORS = { 0:'\\x1b[0m', 1:'\\x1b[36m', 2:'\\x1b[36m', 3:'\\x1b[33m',\n"
"    4:'\\x1b[32m', 5:'\\x1b[35m', 6:'\\x1b[31m', 7:'\\x1b[34m', 8:'\\x1b[34m',\n"
"    9:'\\x1b[35m', 10:'\\x1b[33m', 11:'\\x1b[36m', 12:'\\x1b[32m', 13:'\\x1b[31m',\n"
"    14:'\\x1b[37m', 15:'\\x1b[35m' };\n"
"\n"
"  function setStatus(text, state) {\n"
"    statusEl.textContent = text;\n"
"    statusEl.className = 'status ' + (state || 'disconnected');\n"
"  }\n"
"\n"
"  /* Send message to host (webview or websocket) */\n"
"  function send(obj) {\n"
"    if (isWebview) {\n"
"      /* webview_bind creates psnd as a callable function */\n"
"      window.psnd(JSON.stringify(obj));\n"
"    } else if (ws && ws.readyState === WebSocket.OPEN) {\n"
"      ws.send(JSON.stringify(obj));\n"
"    }\n"
"  }\n"
"\n"
"  /* Connect to server (websocket mode only) */\n"
"  function connect() {\n"
"    if (isWebview) {\n"
"      /* In webview mode, we're always connected */\n"
"      setStatus('Connected', 'connected');\n"
"      send({cmd: 'resize', rows: term.rows, cols: term.cols});\n"
"      send({cmd: 'snapshot'});\n"
"      return;\n"
"    }\n"
"    if (ws && ws.readyState === WebSocket.OPEN) return;\n"
"    setStatus('Connecting...', 'connecting');\n"
"    var proto = location.protocol === 'https:' ? 'wss:' : 'ws:';\n"
"    var tok = new URLSearchParams(location.search).get('token') || '';\n"
"    ws = new WebSocket(proto + '//' + location.host + '/ws?token=' +\n"
"                       encodeURIComponent(tok));\n"
"    ws.onopen = function() {\n"
"      setStatus('Connected', 'connected');\n"
"      send({cmd: 'resize', rows: term.rows, cols: term.cols});\n"
"      send({cmd: 'snapshot'});\n"
"    };\n"
"    ws.onclose = function() {\n"
"      setStatus('Disconnected', 'disconnected'); ws = null;\n"
"      if (!reconnectTimeout) reconnectTimeout = setTimeout(function() {\n"
"        reconnectTimeout = null; connect();\n"
"      }, 2000);\n"
"    };\n"
"    ws.onerror = function() { setStatus('Error', 'disconnected'); };\n"
"    ws.onmessage = function(e) {\n"
"      try { handleMessage(JSON.parse(e.data)); } catch(err) {}\n"
"    };\n"
"  }\n"
"\n"
"  /* Handle incoming message from host */\n"
"  function handleMessage(msg) {\n"
"    var vm = msg.viewmodel || (msg.type === 'update' ? msg.viewmodel : null);\n"
"    if (vm) renderViewModel(vm);\n"
"  }\n"
"\n"
"  /* Expose handler for webview mode */\n"
"  window.psndHandleMessage = handleMessage;\n"
"\n"
"  function renderViewModel(vm) {\n"
"    if (!vm) return;\n"
"    term.reset();\n"
"    if (vm.rows_content) {\n"
"      for (var i = 0; i < vm.rows_content.length; i++) {\n"
"        var row = vm.rows_content[i], line = '';\n"
"        if (vm.gutter_width > 0 && row.row_num > 0) {\n"
"          var ln = String(row.row_num);\n"
"          while (ln.length < vm.gutter_width - 1) ln = ' ' + ln;\n"
"          line += '\\x1b[90m' + ln + ' \\x1b[0m';\n"
"        } else if (vm.gutter_width > 0) {\n"
"          var sp = ''; for (var k = 0; k < vm.gutter_width - 1; k++) sp += ' ';\n"
"          line += '\\x1b[90m' + sp + '~ \\x1b[0m';\n"
"        }\n"
"        if (row.segments) {\n"
"          var lastHl = -1;\n"
"          for (var j = 0; j < row.segments.length; j++) {\n"
"            var seg = row.segments[j];\n"
"            if (seg.hl_type !== lastHl) { line += HL_COLORS[seg.hl_type] || '\\x1b[0m'; lastHl = seg.hl_type; }\n"
"            if (seg.selected) line += '\\x1b[7m';\n"
"            line += seg.text || '';\n"
"            if (seg.selected) line += '\\x1b[27m';\n"
"          }\n"
"          line += '\\x1b[0m';\n"
"        }\n"
"        if (i < vm.rows_content.length - 1) term.writeln(line); else term.write(line);\n"
"      }\n"
"    }\n"
"    if (vm.cursor && vm.cursor.visible) {\n"
"      term.write('\\x1b[' + vm.cursor.row + ';' + vm.cursor.col + 'H');\n"
"    }\n"
"    if (vm.status) {\n"
"      modeEl.textContent = vm.status.mode || '';\n"
"      filenameEl.textContent = (vm.status.filename || '[No Name]') + (vm.status.dirty ? ' [+]' : '');\n"
"      positionEl.textContent = 'Ln ' + (vm.status.current_row || 1) + ' / ' + (vm.status.numrows || 1);\n"
"    }\n"
"    if (vm.message) messageEl.textContent = vm.message;\n"
"  }\n"
"\n"
"  var SPECIAL_KEYS = { 'Escape': 27, 'Enter': 13, 'Backspace': 127, 'Tab': 9,\n"
"    'ArrowLeft': 1000, 'ArrowRight': 1001, 'ArrowUp': 1002, 'ArrowDown': 1003,\n"
"    'Delete': 1008, 'Home': 1009, 'End': 1010, 'PageUp': 1011, 'PageDown': 1012 };\n"
"\n"
"  term.onKey(function(e) {\n"
"    var key = e.key, dom = e.domEvent;\n"
"    var mods = 0;\n"
"    if (dom.ctrlKey) mods |= 1;\n"
"    if (dom.altKey) mods |= 2;\n"
"    if (dom.shiftKey) mods |= 4;\n"
"    var code;\n"
"    if (SPECIAL_KEYS[dom.key] !== undefined) code = SPECIAL_KEYS[dom.key];\n"
"    else if (key.length === 1) {\n"
"      code = key.charCodeAt(0);\n"
"      if (dom.ctrlKey && code >= 97 && code <= 122) code = code - 96;\n"
"      else if (dom.ctrlKey && code >= 65 && code <= 90) code = code - 64;\n"
"    } else return;\n"
"    if (dom.ctrlKey) dom.preventDefault();\n"
"    send({cmd: 'event', type: 'key', code: code, modifiers: mods});\n"
"  });\n"
"\n"
"  document.addEventListener('keydown', function(e) {\n"
"    if (e.ctrlKey && !e.altKey && !e.metaKey) {\n"
"      var k = e.key.toLowerCase();\n"
"      if (k === 'p' || k === 'e' || k === 's' || k === 'q' || k === 'f' || k === 'g' || k === 'r') {\n"
"        e.preventDefault();\n"
"      }\n"
"    }\n"
"  });\n"
"\n"
"  window.addEventListener('resize', function() {\n"
"    fitAddon.fit();\n"
"    send({cmd: 'resize', rows: term.rows, cols: term.cols});\n"
"    send({cmd: 'snapshot'});\n"
"  });\n"
"\n"
"  /* Mouse click to position cursor */\n"
"  var termEl = document.getElementById('terminal');\n"
"  var mouseDownPos = null;\n"
"  var isSelecting = false;\n"
"\n"
"  termEl.addEventListener('mousedown', function(e) {\n"
"    if (e.button !== 0) return;\n"
"    mouseDownPos = { x: e.clientX, y: e.clientY };\n"
"    isSelecting = false;\n"
"  });\n"
"\n"
"  termEl.addEventListener('mousemove', function(e) {\n"
"    if (mouseDownPos && (Math.abs(e.clientX - mouseDownPos.x) > 3 || Math.abs(e.clientY - mouseDownPos.y) > 3)) {\n"
"      isSelecting = true;\n"
"    }\n"
"  });\n"
"\n"
"  termEl.addEventListener('mouseup', function(e) {\n"
"    if (e.button !== 0 || !mouseDownPos) { mouseDownPos = null; return; }\n"
"    if (!isSelecting) {\n"
"      var screen = termEl.querySelector('.xterm-screen');\n"
"      if (screen) {\n"
"        var rect = screen.getBoundingClientRect();\n"
"        var cellW = rect.width / term.cols;\n"
"        var cellH = rect.height / term.rows;\n"
"        var x = Math.floor((e.clientX - rect.left) / cellW) + 1;\n"
"        var y = Math.floor((e.clientY - rect.top) / cellH) + 1;\n"
"        if (x > 0 && y > 0 && x <= term.cols && y <= term.rows) {\n"
"          send({cmd: 'event', type: 'mouse', x: x, y: y, button: 0, pressed: 1});\n"
"        }\n"
"      }\n"
"    }\n"
"    mouseDownPos = null;\n"
"    isSelecting = false;\n"
"  });\n"
"\n"
"\n"
"  termEl.addEventListener('contextmenu', function(e) { e.preventDefault(); });\n"
"\n"
"  document.getElementById('btn-play').addEventListener('click', function() {\n"
"    send({cmd: 'event', type: 'key', code: 16, modifiers: 1}); term.focus();\n"
"  });\n"
"  document.getElementById('btn-stop').addEventListener('click', function() {\n"
"    send({cmd: 'event', type: 'key', code: 7, modifiers: 1}); term.focus();\n"
"  });\n"
"  document.getElementById('btn-eval').addEventListener('click', function() {\n"
"    send({cmd: 'event', type: 'key', code: 5, modifiers: 1}); term.focus();\n"
"  });\n"
"\n"
"  connect();\n"
"  term.focus();\n"
"})();\n"
"  </script>\n"
"</body>\n"
"</html>\n";

#endif /* LOKI_HOST_WEB_UI_H */
